import React, { useState } from 'react';
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Button,
  Container,
  Grid,
  Link,
  styled,
  Typography,
} from '@mui/material';
import {
  AutoAwesome,
  Code,
  Devices,
  EmojiEvents,
  ExpandMore,
  FileDownload,
  Groups,
  RocketLaunch,
} from '@mui/icons-material';
import { useNavigate, Link as RouterLink } from 'react-router-dom';
import { signInAnonymously, UserCredential } from 'firebase/auth';
import {
  addDoc,
  collection,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';
import { useAuth, useFirestore, useSigninCheck } from '../../firebase';
import { MindMap } from '../../types';
import { createRootNode } from '../../nodeOps';

const Content = styled(Container)(({ theme }) => ({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  textAlign: 'center',
  paddingTop: theme.spacing(4),
  paddingBottom: theme.spacing(4),
  [theme.breakpoints.up('md')]: {
    paddingTop: theme.spacing(16),
    paddingBottom: theme.spacing(8),
    flexDirection: 'row',
    alignItems: 'flex-start',
    textAlign: 'left',
  },
}));

const Title = styled('h1')(({ theme }) => ({
  marginLeft: -12,
  whiteSpace: 'nowrap',
  textIndent: '.7rem',
  fontSize: 28,
  [theme.breakpoints.up('md')]: {
    fontSize: 56,
  },
}));

const Logo = styled('img')(({ theme }) => ({
  flexShrink: 0,
  width: 250,
  height: 250,
  marginBottom: theme.spacing(2),
  [theme.breakpoints.up('md')]: {
    margin: 50,
    marginRight: theme.spacing(8),
    width: 350,
    height: 350,
  },
}));

const features = [
  {
    icon: <AutoAwesome />,
    title: 'AI-assisted brainstorming',
    text: 'Stuck? Ask for ideas on any bubble and get related suggestions generated by AI and word associations.',
  },
  {
    icon: <Groups />,
    title: 'Real-time collaboration',
    text: 'Share a link and build together. Everyone sees changes live as the map grows.',
  },
  {
    icon: <RocketLaunch />,
    title: 'Start in one click',
    text: 'No sign-up needed — click once and you are mapping. Claim your maps with a free account whenever you are ready.',
  },
  {
    icon: <Devices />,
    title: 'Works on any device',
    text: 'Built for keyboard-and-mouse speed and touchscreen ease, and installable as an app on desktop and mobile.',
  },
  {
    icon: <FileDownload />,
    title: 'Export your maps',
    text: 'Take your ideas with you as PNG images, SVG vector graphics, or Markdown outlines.',
  },
  {
    icon: <Code />,
    title: 'Free and open source',
    text: 'Bubble Map is completely free to use, and the entire project is open source on GitHub.',
  },
];

const steps = [
  {
    title: 'Create',
    text: 'Start a mind map with a single click — no account or download required.',
  },
  {
    title: 'Grow',
    text: 'Add bubbles with a keystroke or a tap, drag them around the canvas, and ask AI for a spark when you need one.',
  },
  {
    title: 'Share',
    text: 'Invite others with a link to build together, then export to PNG, SVG, or Markdown.',
  },
];

const faqs = [
  {
    question: 'Is Bubble Map really free?',
    answer:
      'Yes. Bubble Map is completely free to use, and the whole project is open source. It began as a student project and won the 2022 Congressional App Challenge (AZ-06).',
  },
  {
    question: 'Do I need an account to make a mind map?',
    answer:
      'No. Click once and a temporary guest account is created for you automatically so your work is saved. You can turn it into a real account later to keep your maps across devices.',
  },
  {
    question: 'How do the AI suggestions work?',
    answer:
      'When you ask for ideas, the text of the selected bubble is sent to AI text-generation and word-association services, which return related ideas you can add to your map with one click.',
  },
  {
    question: 'Can I collaborate with other people?',
    answer:
      'Yes. Make a map public and share the link so others can view it, or enable public editing to brainstorm together — changes appear live for everyone.',
  },
  {
    question: 'Can I export my mind maps?',
    answer:
      'Yes. You can export any map as a PNG image, an SVG vector graphic, or a Markdown outline.',
  },
  {
    question: 'Is my data private?',
    answer:
      'Your maps are private by default and only visible to others if you share them. See our privacy policy for the full details of what we collect and why.',
  },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map(({ question, answer }) => ({
    '@type': 'Question',
    name: question,
    acceptedAnswer: { '@type': 'Answer', text: answer },
  })),
};

const SectionHeading = ({ children }: { children: React.ReactNode }) => (
  <Typography
    variant="h4"
    component="h2"
    align="center"
    sx={{ mb: { xs: 3, md: 5 } }}
  >
    {children}
  </Typography>
);

const HomePage = () => {
  const auth = useAuth();
  const firestore = useFirestore();
  const navigate = useNavigate();
  const signInCheck = useSigninCheck().data;
  const [creating, setCreating] = useState(false);

  const mindmapsCollection = collection(firestore, 'mindmaps');

  const createMindMap = (title: string, user: UserCredential) => {
    const newDocData: MindMap = {
      metadata: {
        createdAt: serverTimestamp() as Timestamp,
        createdBy: user.user.uid,
        updatedAt: serverTimestamp() as Timestamp,
        updatedBy: user.user.uid,
        everUpdatedBy: [user.user.uid],
      },
      nodes: [createRootNode(title)],
      permissions: {
        owner: user.user.uid,
        canPublicEdit: false,
        isPublic: false,
      },
      title,
    };
    addDoc(mindmapsCollection, newDocData).then((newDoc) => {
      navigate(`/mindmaps/${newDoc.id}`);
    });
  };

  const primaryCta = !signInCheck.user ? (
    <Button
      onClick={() => {
        setCreating(true);
        signInAnonymously(auth)
          .then((user) => createMindMap('Untitled MindMap', user))
          .catch(() => {
            setCreating(false);
          });
      }}
      disabled={creating}
      variant="contained"
      size="large"
    >
      Create Your First MindMap
    </Button>
  ) : (
    <Button
      onClick={() => navigate('/mindmaps')}
      variant="contained"
      size="large"
    >
      Browse Your Mindmaps
    </Button>
  );

  return (
    <Box component="main">
      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <Content maxWidth="md">
        <Logo src="/assets/logos/Bubble Map Logo.svg" alt="Bubble Map logo" />
        <div>
          <Title>Bubble Map</Title>
          <Typography
            variant="h4"
            component="p"
            color="inherit"
            style={{ fontWeight: 'bold' }}
          >
            Free, AI-Assisted
            <br /> <b>Mind Mapping</b>
          </Typography>
          <Typography
            variant="body1"
            color="text.secondary"
            sx={{ mt: 2, maxWidth: '36rem' }}
          >
            Brainstorm on an infinite canvas: grow ideas bubble by bubble,
            invite others to edit live, and let AI suggest your next idea when
            you are stuck. Nothing to install — it runs in your browser on
            desktop and mobile.
          </Typography>
          <Box sx={{ mt: 3 }}>{primaryCta}</Box>
          <Typography
            variant="body2"
            color="text.secondary"
            sx={{
              mt: 2,
              display: 'flex',
              alignItems: 'center',
              gap: 1,
              justifyContent: { xs: 'center', md: 'flex-start' },
            }}
          >
            <EmojiEvents fontSize="small" aria-hidden />
            Winner of the 2022 Congressional App Challenge (AZ-06)
          </Typography>
        </div>
      </Content>

      <Container
        component="section"
        maxWidth="md"
        sx={{ py: { xs: 6, md: 8 } }}
      >
        <SectionHeading>Everything you need to think visually</SectionHeading>
        <Grid container spacing={4}>
          {features.map(({ icon, title, text }) => (
            <Grid key={title} size={{ xs: 12, sm: 6, md: 4 }}>
              <Box
                aria-hidden
                sx={{
                  width: 48,
                  height: 48,
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  bgcolor: 'primary.main',
                  color: 'primary.contrastText',
                  mb: 1.5,
                }}
              >
                {icon}
              </Box>
              <Typography variant="h6" component="h3" sx={{ mb: 0.5 }}>
                {title}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {text}
              </Typography>
            </Grid>
          ))}
        </Grid>
      </Container>

      <Container
        component="section"
        maxWidth="md"
        sx={{ py: { xs: 6, md: 8 } }}
      >
        <SectionHeading>How it works</SectionHeading>
        <Grid container spacing={4}>
          {steps.map(({ title, text }, index) => (
            <Grid key={title} size={{ xs: 12, md: 4 }}>
              <Box
                aria-hidden
                sx={{
                  width: 40,
                  height: 40,
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: 2,
                  borderColor: 'primary.main',
                  color: 'primary.main',
                  fontWeight: 'bold',
                  mb: 1.5,
                }}
              >
                {index + 1}
              </Box>
              <Typography variant="h6" component="h3" sx={{ mb: 0.5 }}>
                {title}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {text}
              </Typography>
            </Grid>
          ))}
        </Grid>
      </Container>

      <Container
        component="section"
        maxWidth="md"
        sx={{ py: { xs: 6, md: 8 } }}
      >
        <SectionHeading>Frequently asked questions</SectionHeading>
        {faqs.map(({ question, answer }) => (
          <Accordion key={question} variant="outlined" disableGutters>
            {/* AccordionSummary already renders inside an <h3> heading. */}
            <AccordionSummary expandIcon={<ExpandMore />}>
              <Typography variant="body1" sx={{ fontWeight: 'bold' }}>
                {question}
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="body2" color="text.secondary">
                {answer}
                {question === 'Is my data private?' && (
                  <>
                    {' '}
                    <Link component={RouterLink} to="/privacy" color="inherit">
                      Read the privacy policy
                    </Link>
                    .
                  </>
                )}
              </Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Container>

      <Container
        component="section"
        maxWidth="md"
        sx={{ py: { xs: 6, md: 8 }, textAlign: 'center' }}
      >
        <Typography variant="h4" component="h2" sx={{ mb: 2 }}>
          Ready to map your ideas?
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
          Your first mind map is one click away — free, no account required.
        </Typography>
        {primaryCta}
      </Container>
    </Box>
  );
};

export default HomePage;
